# Site settings
title: A blog about Dr. Jennifer R. Shloming
description: Currently called: Professor / Jenn / Mommy / more
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anon Developer
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: jennifer_shloming@fitnyc.edu
instagram: math_d0rk
github_username:  jennifershloming
pinterest: https://www.pinterest.com/mathd0rk/for-my-courses/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
