# Site settings
title: Dr. Jennifer R. Shloming
description: Some of my names include Professor and Jenn and Mommy and more
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dr. Jennifer R. Shloming
user_description: Educator at SUNY Fashion Institute of Technology for over a decade. Open SUNY Online Teaching Ambassador <a href="https://innovate.suny.edu/onlineteaching/engage/ambassadorprogram/ambassadors/2019ambassador-shloming/">My Ambassador Profile</a>. Currently the Assistant Chairperson of the Science and Mathematics Department. New Yorker who falls in love with the City daily. <a href="https://jennsnyc.tumblr.com/">NYC cell phone pictures</a>. When my kids let me, <a href="https://www.goodreads.com/user/show/7651021-jenn/">I love to read</a>.
user_title: Assistant Professor of Mathematics
email: jennifer_shloming@fitnyc.edu
instagram: math_d0rk
github_username:  jennifershloming
pinterest: https://www.pinterest.com/mathd0rk/for-my-courses/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
